
-------------------------------------
--CREATE SNOWPIPE ENDPOINT"PIPELINE_GROUP02"

--show stages in database "PIPELINE_GROUP02"
--show file formats in database "PIPELINE_GROUP02"

alter user HANK0720 set rsa_public_key = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxP20oUpVwtPYPuGnsyou
ySuD685+YMOUEQI583TSom5f4GBikCRGmrrF6oFMQjj74iYNULxGe2pYCnDOzPnF
VAZSt5uq+Mg70yopks+GSzVIkaXSYJIk0A2zC3VrTF6iS3ze8pwsF2sfludgI0um
kwcY+iTgnkNj000rm3LswMoN3Y/7/aUniDmB3OYHdUZkSi4/pIlrwhgBgxU1qwA/
uEYNJ27RB0J7VrIGVDuxjY/NDtkrEepuQqtv/o7zhtr4SnLC4EBGg9QhkehHRcJN
0rAkPzWFok9Q3JAGpG0JTuD3LBV08X5+CLGXQlSwiA+0/tqekuvRZZ9i/YpIAtJZ
mQIDAQAB'

drop stage "EDUCATIONDATA"."STAGGINGDWH".SNOWFLAKE_PUSH;
drop pipe "EDUCATIONDATA"."STAGGINGDWH".mypipe;

CREATE STAGE "EDUCATIONDATA"."STAGGINGDWH".SNOWFLAKE_PUSH;

create pipe "EDUCATIONDATA"."STAGGINGDWH".mypipe
if not exists as copy into "EDUCATIONDATA"."STAGGINGDWH"."FACTTRANSACTION" from @"EDUCATIONDATA"."STAGGINGDWH"."SNOWFLAKE_PUSH"
file_format = CSV;


LIST @SNOWFLAKE_PUSH

select SYSTEM$PIPE_STATUS('"EDUCATIONDATA"."STAGGINGDWH".mypipe')

